<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Madoc platform'))->setSeparator(' · ');
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/frame.css'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700italic,700');
$this->headLink()->prependStylesheet('//stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css');
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->trigger('view.layout');
$title = $this->pageTitle($site->title());
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headStyle(); ?>
</head>

<?php echo $this->htmlElement('body'); ?>

<?php echo $this->userBar(); ?>
<?php /** @var $site \Omeka\Api\Representation\SiteRepresentation */ ?>
<header id="llgc_branded_frame_header" class="container">
<!-- llgc logo -->
<div id="llgc_header_logo" class="col-xs-10 col-sm-3 col-md-4 col-lg-5">
            <a href="https://www.library.wales/">
                <img src="https://www.llgc.org.uk/fileadmin/templates/assets/branded_frame/img/llgc_logo.png" alt="Link to the Library's home page" id="llgc_branded_frame_logo" title="Back to the Library's home page">
            </a>
        </div>
    <div id="search">
        <?php echo $this->partial('common/search-form'); ?>
    </div>
    <?php if ($this->siteSetting('i18n-language-list', '')): ?>
        <?php try { echo $this->partial('common/locale-helper'); } catch (\Throwable $e) {} ?>
    <?php endif; ?>
    <nav>
        <?php
        echo $site->publicNav()->menu()->renderMenu(null, [
            'maxDepth' => $this->themeSetting('nav_depth') - 1
        ]);
        ?>

    </nav>
    <?php echo $this->messages(); ?>
</header>
<main id="content" role="main">
    <?php print $this->content; ?>
</main>
<footer>

    <div class="footer-inner">
        <?php if ($footerContent = $this->themeSetting('footer')): ?>
            <?php echo $footerContent; ?>
        <?php else: ?>
            <?php echo $this->translate('Powered by Madoc Platform running on Omeka S'); ?>
        <?php endif; ?>
    </div>
</footer>
<?php echo $this->headScript(); ?>
</body>
</html>
