-- MySQL dump 10.13  Distrib 5.7.19, for Linux (x86_64)
--
-- Host: localhost    Database: omeka_s
-- ------------------------------------------------------
-- Server version	5.7.19

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

LOCK TABLES `site` WRITE;
/*!40000 ALTER TABLE `site` DISABLE KEYS */;
INSERT INTO `site` VALUES (1,1,'war-tribunal-records','nlw-madoc-theme','Cardiganshire Great War Tribunal (Appeals) records','[{\"type\":\"page\",\"data\":{\"label\":\"\",\"id\":1},\"links\":[]},{\"type\":\"url\",\"data\":{\"label\":\"left\",\"url\":\"#\"},\"links\":[{\"type\":\"url\",\"data\":{\"label\":\"View all collections\",\"url\":\"\\/s\\/war-tribunal-records\\/iiif\\/collection\\/213\"},\"links\":[]},{\"type\":\"page\",\"data\":{\"label\":\"\",\"id\":3},\"links\":[]},{\"type\":\"page\",\"data\":{\"label\":\"\",\"id\":5},\"links\":[]}]},{\"type\":\"url\",\"data\":{\"label\":\"right\",\"url\":\"#\"},\"links\":[{\"type\":\"url\",\"data\":{\"label\":\"Current projects\",\"url\":\"#\"},\"links\":[{\"type\":\"url\",\"data\":{\"label\":\"Cardiganshire Tribunal records\",\"url\":\"#\"},\"links\":[]}]},{\"type\":\"page\",\"data\":{\"label\":\"\",\"id\":6},\"links\":[]}]}]','{\"resource_class_id\":\"\",\"property\":[{\"joiner\":\"and\",\"property\":\"\",\"type\":\"eq\",\"text\":\"\"}],\"site_id\":\"\",\"item_set_id\":[\"\"],\"o:site_item_set\":[{\"o:item_set\":{\"o:id\":\"153\"}},{\"o:item_set\":{\"o:id\":\"158\"}},{\"o:item_set\":{\"o:id\":\"162\"}},{\"o:item_set\":{\"o:id\":\"213\"}}]}','2017-11-27 13:33:13','2018-05-16 14:46:48',1, NULL),
                          (6,2,'test-jan','nlw-madoc-theme','Test January','[{\"type\":\"page\",\"data\":{\"label\":\"\",\"id\":15},\"links\":[]},{\"type\":\"url\",\"data\":{\"label\":\"left\",\"url\":\"#\"},\"links\":[{\"type\":\"url\",\"data\":{\"label\":\"Collection\",\"url\":\"https:\\/\\/crowd.library.wales\\/en\\/s\\/test-jan\\/iiif\\/collection\\/193\"},\"links\":[]}]},{\"type\":\"url\",\"data\":{\"label\":\"right\",\"url\":\"#\"},\"links\":[]}]','{\"resource_class_id\":\"\",\"property\":[{\"joiner\":\"and\",\"property\":\"\",\"type\":\"eq\",\"text\":\"\"}],\"site_id\":\"\",\"item_set_id\":[\"\"],\"o:site_item_set\":[{\"o:item_set\":{\"o:id\":\"211\"}},{\"o:item_set\":{\"o:id\":\"193\"}}]}','2018-01-15 11:38:27','2018-11-01 15:03:26',0, NULL),
                          (8,165,'livingstone','nlw-madoc-theme','Gwilym Livingstone Evans','[{\"type\":\"page\",\"data\":{\"label\":\"\",\"id\":18},\"links\":[]},{\"type\":\"url\",\"data\":{\"label\":\"left\",\"url\":\"#\"},\"links\":[{\"type\":\"url\",\"data\":{\"label\":\"Home\",\"url\":\"https:\\/\\/crowd.library.wales\\/en\\/s\\/livingstone\\/page\\/home\"},\"links\":[]},{\"type\":\"url\",\"data\":{\"label\":\"View all collections\",\"url\":\"https:\\/\\/crowd.library.wales\\/en\\/s\\/livingstone\\/iiif\\/collection\\/233\"},\"links\":[]},{\"type\":\"page\",\"data\":{\"label\":\"\",\"id\":19},\"links\":[]},{\"type\":\"page\",\"data\":{\"label\":\"\",\"id\":20},\"links\":[]}]},{\"type\":\"url\",\"data\":{\"label\":\"right\",\"url\":\"#\"},\"links\":[{\"type\":\"page\",\"data\":{\"label\":\"\",\"id\":21},\"links\":[]},{\"type\":\"url\",\"data\":{\"label\":\"Current Projects\",\"url\":\"#\"},\"links\":[{\"type\":\"url\",\"data\":{\"label\":\"GLE 2\",\"url\":\"https:\\/\\/crowd.library.wales\\/en\\/s\\/livingstone2\"},\"links\":[]},{\"type\":\"url\",\"data\":{\"label\":\"GLE 3\",\"url\":\"https:\\/\\/crowd.library.wales\\/en\\/s\\/livingstone3\"},\"links\":[]}]}]}]','{\"resource_class_id\":\"\",\"property\":[{\"joiner\":\"and\",\"property\":\"\",\"type\":\"eq\",\"text\":\"\"}],\"site_id\":\"\",\"item_set_id\":[\"\"],\"o:site_item_set\":[{\"o:item_set\":{\"o:id\":\"546\"}},{\"o:item_set\":{\"o:id\":\"233\"}}]}','2018-05-04 13:11:39','2018-11-13 14:37:33',1, NULL),
                          (10,165,'home','nlw-madoc-theme','Main home page','[{\"type\":\"page\",\"data\":{\"label\":\"Hafan | Home\",\"id\":29},\"links\":[]}]','{\"resource_class_id\":\"\",\"property\":[{\"joiner\":\"and\",\"property\":\"\",\"type\":\"eq\",\"text\":\"\"}],\"site_id\":\"\",\"item_set_id\":[\"\"]}','2018-07-24 11:52:33','2018-08-03 13:44:00',1, NULL),
                          (11,165,'kyffin','nlw-madoc-theme','Kyffin Diaries','[{\"type\":\"page\",\"data\":{\"label\":\"\",\"id\":38},\"links\":[]},{\"type\":\"url\",\"data\":{\"label\":\"left\",\"url\":\"#\"},\"links\":[{\"type\":\"url\",\"data\":{\"label\":\"Home\",\"url\":\"https:\\/\\/crowd.library.wales\\/en\\/s\\/kyffin\\/page\\/home\"},\"links\":[]},{\"type\":\"url\",\"data\":{\"label\":\"View all collections\",\"url\":\"https:\\/\\/crowd.library.wales\\/en\\/s\\/kyffin\\/iiif\\/collection\\/547\"},\"links\":[]},{\"type\":\"page\",\"data\":{\"label\":\"\",\"id\":32},\"links\":[]},{\"type\":\"page\",\"data\":{\"label\":\"\",\"id\":33},\"links\":[]}]},{\"type\":\"url\",\"data\":{\"label\":\"right\",\"url\":\"#\"},\"links\":[{\"type\":\"page\",\"data\":{\"id\":39,\"label\":\"\"},\"links\":[]}]}]','{\"resource_class_id\":\"\",\"property\":[{\"joiner\":\"and\",\"property\":\"\",\"type\":\"eq\",\"text\":\"\"}],\"site_id\":\"\",\"item_set_id\":[\"\"],\"o:site_item_set\":[{\"o:item_set\":{\"o:id\":\"562\"}}]}','2018-09-27 13:12:13','2018-09-27 13:55:24',1, NULL),
                          (12,165,'dcharries','nlw-madoc-theme','DC Harries Portraits','[{\"type\":\"browse\",\"data\":{\"label\":\"Browse\",\"query\":\"\"},\"links\":[]},{\"type\":\"url\",\"data\":{\"label\":\"left\",\"url\":\"#\"},\"links\":[{\"type\":\"page\",\"data\":{\"label\":\"\",\"id\":40},\"links\":[]},{\"type\":\"url\",\"data\":{\"label\":\"View the photos\",\"url\":\"https:\\/\\/crowd.library.wales\\/en\\/s\\/dcharries\\/iiif\\/manifest\\/569\"},\"links\":[]},{\"type\":\"page\",\"data\":{\"label\":\"\",\"id\":41},\"links\":[]},{\"type\":\"page\",\"data\":{\"label\":\"\",\"id\":42},\"links\":[]}]},{\"type\":\"url\",\"data\":{\"label\":\"right\",\"url\":\"#\"},\"links\":[{\"type\":\"page\",\"data\":{\"label\":\"\",\"id\":43},\"links\":[]}]}]','{\"resource_class_id\":\"\",\"property\":[{\"joiner\":\"and\",\"property\":\"\",\"type\":\"eq\",\"text\":\"\"}],\"site_id\":\"\",\"item_set_id\":[\"\"],\"o:site_item_set\":[{\"o:item_set\":{\"o:id\":\"570\"}}]}','2018-11-01 14:52:25','2018-11-01 16:36:16',1, NULL),
                          (13,165,'livingstone2','nlw-madoc-theme','Gwilym Livingstone Evans 2','[{\"type\":\"url\",\"data\":{\"label\":\"left\",\"url\":\"#\"},\"links\":[{\"type\":\"page\",\"data\":{\"label\":\"\",\"id\":48},\"links\":[]},{\"type\":\"url\",\"data\":{\"label\":\"View all collections\",\"url\":\"https:\\/\\/crowd.library.wales\\/en\\/s\\/livingstone2\\/iiif\\/collection\\/1053\"},\"links\":[]},{\"type\":\"page\",\"data\":{\"label\":\"\",\"id\":50},\"links\":[]},{\"type\":\"page\",\"data\":{\"label\":\"\",\"id\":51},\"links\":[]}]},{\"type\":\"url\",\"data\":{\"label\":\"right\",\"url\":\"#\"},\"links\":[{\"type\":\"page\",\"data\":{\"label\":\"\",\"id\":52},\"links\":[]},{\"type\":\"url\",\"data\":{\"label\":\"Current Projects\",\"url\":\"#\"},\"links\":[{\"type\":\"url\",\"data\":{\"label\":\"GLE  1\",\"url\":\"https:\\/\\/crowd.library.wales\\/en\\/s\\/livingstone\"},\"links\":[]},{\"type\":\"url\",\"data\":{\"label\":\"GLE 3\",\"url\":\"https:\\/\\/crowd.library.wales\\/en\\/s\\/livingstone3\"},\"links\":[]}]}]}]','{\"resource_class_id\":\"\",\"property\":[{\"joiner\":\"and\",\"property\":\"\",\"type\":\"eq\",\"text\":\"\"}],\"site_id\":\"\",\"item_set_id\":[\"\"],\"o:site_item_set\":[{\"o:item_set\":{\"o:id\":\"546\"}},{\"o:item_set\":{\"o:id\":\"571\"}}]}','2018-11-12 12:22:25','2018-11-13 14:43:24',1, NULL),
                          (14,165,'livingstone3','nlw-madoc-theme','Gwilym Livingstone Evans 3','[{\"type\":\"page\",\"data\":{\"label\":\"\",\"id\":49},\"links\":[]},{\"type\":\"url\",\"data\":{\"label\":\"left\",\"url\":\"#\"},\"links\":[{\"type\":\"url\",\"data\":{\"label\":\"Home\",\"url\":\"https:\\/\\/crowd.library.wales\\/en\\/s\\/livingstone3\\/page\\/home\"},\"links\":[]},{\"type\":\"url\",\"data\":{\"label\":\"View all collections\",\"url\":\"https:\\/\\/crowd.library.wales\\/en\\/s\\/livingstone3\\/iiif\\/collection\\/853\"},\"links\":[]},{\"type\":\"page\",\"data\":{\"label\":\"\",\"id\":57},\"links\":[]},{\"type\":\"page\",\"data\":{\"label\":\"\",\"id\":58},\"links\":[]}]},{\"type\":\"url\",\"data\":{\"label\":\"right\",\"url\":\"#\"},\"links\":[{\"type\":\"page\",\"data\":{\"label\":\"\",\"id\":59},\"links\":[]},{\"type\":\"url\",\"data\":{\"label\":\"Current Projects\",\"url\":\"#\"},\"links\":[{\"type\":\"url\",\"data\":{\"label\":\"GLE 1\",\"url\":\"https:\\/\\/crowd.library.wales\\/en\\/s\\/livingstone\\/page\\/home\"},\"links\":[]},{\"type\":\"url\",\"data\":{\"label\":\"GLE2\",\"url\":\"https:\\/\\/crowd.library.wales\\/en\\/s\\/livingstone2\\/page\\/home\"},\"links\":[]}]}]}]','{\"resource_class_id\":\"\",\"property\":[{\"joiner\":\"and\",\"property\":\"\",\"type\":\"eq\",\"text\":\"\"}],\"site_id\":\"\",\"item_set_id\":[\"\"],\"o:site_item_set\":[{\"o:item_set\":{\"o:id\":\"546\"}}]}','2018-11-13 12:25:04','2018-11-13 14:35:35',1, NULL);
/*!40000 ALTER TABLE `site` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
